var combinaisons = [
    { "combinaison": "AA", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "AKs", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "AQs", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "AKo", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "KK", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "QQ", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "JJ", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "TT", "pourcentage": 4, "rate": "★★★★★" },
    { "combinaison": "99", "pourcentage": 4, "rate": "★★★★★" },

    { "combinaison": "AJs", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "ATs", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "KQs", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "KJs", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "KTs", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "AQo", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "QJs", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "AJo", "pourcentage": 8, "rate": "★★★★☆" },
    { "combinaison": "88", "pourcentage": 8, "rate": "★★★★☆" },

    { "combinaison": "A9s", "pourcentage": 12, "rate": "★★★☆☆" },
    { "combinaison": "KQo", "pourcentage": 12, "rate": "★★★☆☆" },
    { "combinaison": "QTs", "pourcentage": 12, "rate": "★★★☆☆" },
    { "combinaison": "KJo", "pourcentage": 12, "rate": "★★★☆☆" },
    { "combinaison": "JTs", "pourcentage": 12, "rate": "★★★☆☆" },
    { "combinaison": "ATo", "pourcentage": 12, "rate": "★★★☆☆" },
    { "combinaison": "77", "pourcentage": 12, "rate": "★★★☆☆" },

    { "combinaison": "A8s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "A7s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "A6s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "A5s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "A4s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "K9s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "K8s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "Q9s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "QJo", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "J9s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "KTo", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "QTo", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "JTo", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "T9s", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "A9o", "pourcentage": 20, "rate": "★★☆☆☆" },
    { "combinaison": "66", "pourcentage": 20, "rate": "★★☆☆☆" },

    { "combinaison": "A3s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "A2s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "K7s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "K6s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "K5s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "Q8s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "Q7s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "J8s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "T8s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "K9o", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "Q9o", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "J9o", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "98s", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "A8o", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "A7o", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "A5o", "pourcentage": 30, "rate": "★☆☆☆☆" },
    { "combinaison": "55", "pourcentage": 30, "rate": "★☆☆☆☆" },
];